remote_theme: BDHU/minimalist
title: "Dev Toolkit"
description: "A curated list of essential development tools."
include:
  - README.md  # Uses README as the homepage for the GitHub Pages site
permalink: /:path/
logo: /assets/img/logo.webp
favicon: true
plugins:
  - jekyll-remote-theme
